<?php
$data = array (
  0 => 
  array (
    'cat_id' => '476',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '6',
  ),
  1 => 
  array (
    'cat_id' => '473',
    'cat_name' => '酒水饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '16',
  ),
  2 => 
  array (
    'cat_id' => '370',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '5',
  ),
  3 => 
  array (
    'cat_id' => '481',
    'cat_name' => '其他产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '477',
    'cat_name' => '粮油干货',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '474',
    'cat_name' => '日用百货',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '199',
  ),
  6 => 
  array (
    'cat_id' => '478',
    'cat_name' => '茶冲/乳品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '475',
    'cat_name' => '厨房调味',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '480',
    'cat_name' => '办公文体',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '471',
    'cat_name' => '饼干糕点',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '482',
    'cat_name' => '糖果/巧克力',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '1',
  ),
  11 => 
  array (
    'cat_id' => '472',
    'cat_name' => '膨化食品',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '483',
    'cat_name' => '坚果蜜饯',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '491',
    'cat_name' => '传统糕点',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '488',
    'cat_name' => '沙琪玛',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '485',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  16 => 
  array (
    'cat_id' => '489',
    'cat_name' => '蛋黄派/巧克力派',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  17 => 
  array (
    'cat_id' => '486',
    'cat_name' => '威化',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '490',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '487',
    'cat_name' => '曲奇',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '494',
    'cat_name' => '麦烧系列',
    'measure_unit' => '',
    'parent_id' => '472',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '492',
    'cat_name' => '薯片',
    'measure_unit' => '',
    'parent_id' => '472',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  22 => 
  array (
    'cat_id' => '493',
    'cat_name' => '薯条',
    'measure_unit' => '',
    'parent_id' => '472',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '501',
    'cat_name' => '水/饮料',
    'measure_unit' => '',
    'parent_id' => '473',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '502',
    'cat_name' => '中外名酒',
    'measure_unit' => '',
    'parent_id' => '473',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '544',
    'cat_name' => '衣物清洁',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '548',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => '18',
  ),
  27 => 
  array (
    'cat_id' => '550',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '552',
    'cat_name' => '纸品/一次性用品',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '26',
  ),
  29 => 
  array (
    'cat_id' => '549',
    'cat_name' => '身体护肤',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '545',
    'cat_name' => '家庭清洁',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => '3',
  ),
  31 => 
  array (
    'cat_id' => '546',
    'cat_name' => '驱虫驱蚊用品',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '551',
    'cat_name' => '女性护理',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '517',
    'cat_name' => '调味酱',
    'measure_unit' => '',
    'parent_id' => '475',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => '1',
  ),
  34 => 
  array (
    'cat_id' => '519',
    'cat_name' => '其他厨房调料',
    'measure_unit' => '',
    'parent_id' => '475',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '516',
    'cat_name' => '调味料',
    'measure_unit' => '',
    'parent_id' => '475',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '594',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '476',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '603',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '477',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '604',
    'cat_name' => '干货系列',
    'measure_unit' => '',
    'parent_id' => '477',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '602',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '477',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '625',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '478',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '626',
    'cat_name' => '茗茶',
    'measure_unit' => '',
    'parent_id' => '478',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '627',
    'cat_name' => '营养保健',
    'measure_unit' => '',
    'parent_id' => '478',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '624',
    'cat_name' => '牛奶',
    'measure_unit' => '',
    'parent_id' => '478',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '648',
    'cat_name' => '办公用品',
    'measure_unit' => '',
    'parent_id' => '480',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '649',
    'cat_name' => '学习用品',
    'measure_unit' => '',
    'parent_id' => '480',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '495',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '482',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  47 => 
  array (
    'cat_id' => '496',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '482',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '498',
    'cat_name' => '炒货系列',
    'measure_unit' => '',
    'parent_id' => '483',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  49 => 
  array (
    'cat_id' => '499',
    'cat_name' => '蜜饯果干',
    'measure_unit' => '',
    'parent_id' => '483',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  50 => 
  array (
    'cat_id' => '500',
    'cat_name' => '话梅',
    'measure_unit' => '',
    'parent_id' => '483',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  51 => 
  array (
    'cat_id' => '497',
    'cat_name' => '坚果休闲',
    'measure_unit' => '',
    'parent_id' => '483',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '507',
    'cat_name' => '咖啡饮料',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '504',
    'cat_name' => '果汁系列',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  54 => 
  array (
    'cat_id' => '508',
    'cat_name' => '功能饮料',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '505',
    'cat_name' => '茶饮料',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  56 => 
  array (
    'cat_id' => '509',
    'cat_name' => '果蔬饮料',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '506',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '503',
    'cat_name' => '纯净水',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  59 => 
  array (
    'cat_id' => '510',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '514',
    'cat_name' => '果酒',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '511',
    'cat_name' => '红酒',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '515',
    'cat_name' => '滋补酒',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '512',
    'cat_name' => '黄酒',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '513',
    'cat_name' => '啤酒系列',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '527',
    'cat_name' => '其他调味料',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '23',
  ),
  66 => 
  array (
    'cat_id' => '524',
    'cat_name' => '味精/鸡精',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
  ),
  67 => 
  array (
    'cat_id' => '521',
    'cat_name' => '醋',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  68 => 
  array (
    'cat_id' => '525',
    'cat_name' => '汤料/炒菜料',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  69 => 
  array (
    'cat_id' => '522',
    'cat_name' => '料酒',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  70 => 
  array (
    'cat_id' => '526',
    'cat_name' => '火锅底料',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  71 => 
  array (
    'cat_id' => '523',
    'cat_name' => '盐',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '520',
    'cat_name' => '酱油',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '38',
  ),
  73 => 
  array (
    'cat_id' => '534',
    'cat_name' => '肉味酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '531',
    'cat_name' => '番茄酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  75 => 
  array (
    'cat_id' => '528',
    'cat_name' => '豆瓣酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  76 => 
  array (
    'cat_id' => '532',
    'cat_name' => '花生酱/芝麻酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '529',
    'cat_name' => '辣椒酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  78 => 
  array (
    'cat_id' => '533',
    'cat_name' => '鱼子酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '530',
    'cat_name' => '沙拉/蛋黄酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '541',
    'cat_name' => '调味汁',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '538',
    'cat_name' => '花椒油',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '542',
    'cat_name' => '生粉/食品添加',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  83 => 
  array (
    'cat_id' => '539',
    'cat_name' => '麻油',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  84 => 
  array (
    'cat_id' => '536',
    'cat_name' => '蚝油',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  85 => 
  array (
    'cat_id' => '543',
    'cat_name' => '其他蛋制品',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '540',
    'cat_name' => '豉油',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  87 => 
  array (
    'cat_id' => '537',
    'cat_name' => '香油',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  88 => 
  array (
    'cat_id' => '558',
    'cat_name' => '除霉剂',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '555',
    'cat_name' => '洗衣皂',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '556',
    'cat_name' => '护理液',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '553',
    'cat_name' => '洗衣粉',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  92 => 
  array (
    'cat_id' => '557',
    'cat_name' => '漂渍剂',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '554',
    'cat_name' => '洗衣液',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
  ),
  94 => 
  array (
    'cat_id' => '561',
    'cat_name' => '洁厕用品',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  95 => 
  array (
    'cat_id' => '565',
    'cat_name' => '垃圾桶',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '562',
    'cat_name' => '香皂',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  97 => 
  array (
    'cat_id' => '559',
    'cat_name' => '洗手液',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '566',
    'cat_name' => '拖把',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  99 => 
  array (
    'cat_id' => '563',
    'cat_name' => '油污清洗剂',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '560',
    'cat_name' => '洗洁精',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '567',
    'cat_name' => '百洁布/钢丝球/锅碗刷',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  102 => 
  array (
    'cat_id' => '564',
    'cat_name' => '垃圾袋',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  103 => 
  array (
    'cat_id' => '661',
    'cat_name' => '保鲜膜/保鲜袋',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
  ),
  104 => 
  array (
    'cat_id' => '571',
    'cat_name' => '花露水',
    'measure_unit' => '',
    'parent_id' => '546',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  105 => 
  array (
    'cat_id' => '568',
    'cat_name' => '灭鼠/杀虫剂',
    'measure_unit' => '',
    'parent_id' => '546',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
  ),
  106 => 
  array (
    'cat_id' => '572',
    'cat_name' => '其他驱虫用品',
    'measure_unit' => '',
    'parent_id' => '546',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  107 => 
  array (
    'cat_id' => '569',
    'cat_name' => '蚊香',
    'measure_unit' => '',
    'parent_id' => '546',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
  ),
  108 => 
  array (
    'cat_id' => '570',
    'cat_name' => '吸湿/防蛀',
    'measure_unit' => '',
    'parent_id' => '546',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '581',
    'cat_name' => '染发',
    'measure_unit' => '',
    'parent_id' => '548',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  110 => 
  array (
    'cat_id' => '582',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '548',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  111 => 
  array (
    'cat_id' => '579',
    'cat_name' => '洗发水',
    'measure_unit' => '',
    'parent_id' => '548',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '40',
  ),
  112 => 
  array (
    'cat_id' => '580',
    'cat_name' => '护发素',
    'measure_unit' => '',
    'parent_id' => '548',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  113 => 
  array (
    'cat_id' => '577',
    'cat_name' => '乳液面霜',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  114 => 
  array (
    'cat_id' => '574',
    'cat_name' => '润肤乳',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '578',
    'cat_name' => '防晒',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '575',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '576',
    'cat_name' => '爽肤水',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '573',
    'cat_name' => '沐浴乳',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
  ),
  119 => 
  array (
    'cat_id' => '584',
    'cat_name' => '牙刷',
    'measure_unit' => '',
    'parent_id' => '550',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '585',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '550',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  121 => 
  array (
    'cat_id' => '583',
    'cat_name' => '牙膏',
    'measure_unit' => '',
    'parent_id' => '550',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '57',
  ),
  122 => 
  array (
    'cat_id' => '587',
    'cat_name' => '卫生护垫',
    'measure_unit' => '',
    'parent_id' => '551',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '588',
    'cat_name' => '私密护理',
    'measure_unit' => '',
    'parent_id' => '551',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  124 => 
  array (
    'cat_id' => '589',
    'cat_name' => '脱毛膏',
    'measure_unit' => '',
    'parent_id' => '551',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  125 => 
  array (
    'cat_id' => '586',
    'cat_name' => '卫生巾',
    'measure_unit' => '',
    'parent_id' => '551',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '593',
    'cat_name' => '一次性纸杯',
    'measure_unit' => '',
    'parent_id' => '552',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  127 => 
  array (
    'cat_id' => '590',
    'cat_name' => '卫生纸',
    'measure_unit' => '',
    'parent_id' => '552',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '662',
    'cat_name' => '桌布系列',
    'measure_unit' => '',
    'parent_id' => '552',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  129 => 
  array (
    'cat_id' => '591',
    'cat_name' => '手纸',
    'measure_unit' => '',
    'parent_id' => '552',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '592',
    'cat_name' => '餐巾纸',
    'measure_unit' => '',
    'parent_id' => '552',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  131 => 
  array (
    'cat_id' => '600',
    'cat_name' => '常温辣味制品',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  132 => 
  array (
    'cat_id' => '597',
    'cat_name' => '火腿肠',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  133 => 
  array (
    'cat_id' => '601',
    'cat_name' => '其它速食品',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  134 => 
  array (
    'cat_id' => '598',
    'cat_name' => '罐头',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  135 => 
  array (
    'cat_id' => '595',
    'cat_name' => '方便面',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  136 => 
  array (
    'cat_id' => '599',
    'cat_name' => '八宝粥',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  137 => 
  array (
    'cat_id' => '596',
    'cat_name' => '方便粉丝/米线',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  138 => 
  array (
    'cat_id' => '609',
    'cat_name' => '花生油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  139 => 
  array (
    'cat_id' => '606',
    'cat_name' => '调和油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '610',
    'cat_name' => '葵花籽油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  141 => 
  array (
    'cat_id' => '607',
    'cat_name' => '菜籽油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  142 => 
  array (
    'cat_id' => '611',
    'cat_name' => '玉米油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  143 => 
  array (
    'cat_id' => '608',
    'cat_name' => '稻米油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  144 => 
  array (
    'cat_id' => '605',
    'cat_name' => '大豆油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '616',
    'cat_name' => '粉丝',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '613',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  147 => 
  array (
    'cat_id' => '617',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  148 => 
  array (
    'cat_id' => '614',
    'cat_name' => '面皮',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  149 => 
  array (
    'cat_id' => '615',
    'cat_name' => '面粉',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  150 => 
  array (
    'cat_id' => '612',
    'cat_name' => '面条',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  151 => 
  array (
    'cat_id' => '622',
    'cat_name' => '海带/干菜',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '619',
    'cat_name' => '木耳/银耳',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '623',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '620',
    'cat_name' => '莲子/枣子',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '621',
    'cat_name' => '菌菇类',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '618',
    'cat_name' => '桂圆/荔枝',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '632',
    'cat_name' => '风味奶',
    'measure_unit' => '',
    'parent_id' => '624',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  158 => 
  array (
    'cat_id' => '629',
    'cat_name' => '儿童奶',
    'measure_unit' => '',
    'parent_id' => '624',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  159 => 
  array (
    'cat_id' => '630',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '624',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  160 => 
  array (
    'cat_id' => '631',
    'cat_name' => '豆奶',
    'measure_unit' => '',
    'parent_id' => '624',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  161 => 
  array (
    'cat_id' => '628',
    'cat_name' => '纯牛奶',
    'measure_unit' => '',
    'parent_id' => '624',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  162 => 
  array (
    'cat_id' => '635',
    'cat_name' => '咖啡粉',
    'measure_unit' => '',
    'parent_id' => '625',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  163 => 
  array (
    'cat_id' => '636',
    'cat_name' => '咖啡伴侣',
    'measure_unit' => '',
    'parent_id' => '625',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '633',
    'cat_name' => '速溶咖啡',
    'measure_unit' => '',
    'parent_id' => '625',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '634',
    'cat_name' => '咖啡豆',
    'measure_unit' => '',
    'parent_id' => '625',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  166 => 
  array (
    'cat_id' => '641',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '626',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  167 => 
  array (
    'cat_id' => '638',
    'cat_name' => '花草茶',
    'measure_unit' => '',
    'parent_id' => '626',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  168 => 
  array (
    'cat_id' => '639',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '626',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '640',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '626',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '637',
    'cat_name' => '乌龙茶',
    'measure_unit' => '',
    'parent_id' => '626',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  171 => 
  array (
    'cat_id' => '645',
    'cat_name' => '鱼油/磷脂',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  172 => 
  array (
    'cat_id' => '642',
    'cat_name' => '蛋白质/氨基酸',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  173 => 
  array (
    'cat_id' => '646',
    'cat_name' => '西洋参/人参',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  174 => 
  array (
    'cat_id' => '643',
    'cat_name' => '维生素/钙',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  175 => 
  array (
    'cat_id' => '647',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  176 => 
  array (
    'cat_id' => '644',
    'cat_name' => '保健饮品/酒',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  177 => 
  array (
    'cat_id' => '655',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '648',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  178 => 
  array (
    'cat_id' => '652',
    'cat_name' => '计算器',
    'measure_unit' => '',
    'parent_id' => '648',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '653',
    'cat_name' => '订书机',
    'measure_unit' => '',
    'parent_id' => '648',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  180 => 
  array (
    'cat_id' => '654',
    'cat_name' => '纸笔系列',
    'measure_unit' => '',
    'parent_id' => '648',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  181 => 
  array (
    'cat_id' => '650',
    'cat_name' => '打印纸',
    'measure_unit' => '',
    'parent_id' => '648',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '658',
    'cat_name' => '橡皮',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  183 => 
  array (
    'cat_id' => '659',
    'cat_name' => '铅笔刀',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  184 => 
  array (
    'cat_id' => '656',
    'cat_name' => '笔',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  185 => 
  array (
    'cat_id' => '660',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  186 => 
  array (
    'cat_id' => '657',
    'cat_name' => '本子',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>