<?php
$data = array (
  476 => 
  array (
    'cat_id' => '476',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => '6',
    'level' => 0,
    'id' => '476',
    'name' => '方便速食',
  ),
  594 => 
  array (
    'cat_id' => '594',
    'cat_name' => '方便速食',
    'measure_unit' => '',
    'parent_id' => '476',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '594',
    'name' => '方便速食',
  ),
  600 => 
  array (
    'cat_id' => '600',
    'cat_name' => '常温辣味制品',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '600',
    'name' => '常温辣味制品',
  ),
  597 => 
  array (
    'cat_id' => '597',
    'cat_name' => '火腿肠',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '597',
    'name' => '火腿肠',
  ),
  601 => 
  array (
    'cat_id' => '601',
    'cat_name' => '其它速食品',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 2,
    'id' => '601',
    'name' => '其它速食品',
  ),
  598 => 
  array (
    'cat_id' => '598',
    'cat_name' => '罐头',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '598',
    'name' => '罐头',
  ),
  595 => 
  array (
    'cat_id' => '595',
    'cat_name' => '方便面',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 2,
    'id' => '595',
    'name' => '方便面',
  ),
  599 => 
  array (
    'cat_id' => '599',
    'cat_name' => '八宝粥',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '599',
    'name' => '八宝粥',
  ),
  596 => 
  array (
    'cat_id' => '596',
    'cat_name' => '方便粉丝/米线',
    'measure_unit' => '',
    'parent_id' => '594',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '596',
    'name' => '方便粉丝/米线',
  ),
  473 => 
  array (
    'cat_id' => '473',
    'cat_name' => '酒水饮料',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '16',
    'level' => 0,
    'id' => '473',
    'name' => '酒水饮料',
  ),
  501 => 
  array (
    'cat_id' => '501',
    'cat_name' => '水/饮料',
    'measure_unit' => '',
    'parent_id' => '473',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '501',
    'name' => '水/饮料',
  ),
  507 => 
  array (
    'cat_id' => '507',
    'cat_name' => '咖啡饮料',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '507',
    'name' => '咖啡饮料',
  ),
  504 => 
  array (
    'cat_id' => '504',
    'cat_name' => '果汁系列',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '504',
    'name' => '果汁系列',
  ),
  508 => 
  array (
    'cat_id' => '508',
    'cat_name' => '功能饮料',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '508',
    'name' => '功能饮料',
  ),
  505 => 
  array (
    'cat_id' => '505',
    'cat_name' => '茶饮料',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 2,
    'id' => '505',
    'name' => '茶饮料',
  ),
  509 => 
  array (
    'cat_id' => '509',
    'cat_name' => '果蔬饮料',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '509',
    'name' => '果蔬饮料',
  ),
  506 => 
  array (
    'cat_id' => '506',
    'cat_name' => '碳酸饮料',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '506',
    'name' => '碳酸饮料',
  ),
  503 => 
  array (
    'cat_id' => '503',
    'cat_name' => '纯净水',
    'measure_unit' => '',
    'parent_id' => '501',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '503',
    'name' => '纯净水',
  ),
  502 => 
  array (
    'cat_id' => '502',
    'cat_name' => '中外名酒',
    'measure_unit' => '',
    'parent_id' => '473',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '502',
    'name' => '中外名酒',
  ),
  510 => 
  array (
    'cat_id' => '510',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '510',
    'name' => '白酒',
  ),
  514 => 
  array (
    'cat_id' => '514',
    'cat_name' => '果酒',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '514',
    'name' => '果酒',
  ),
  511 => 
  array (
    'cat_id' => '511',
    'cat_name' => '红酒',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '511',
    'name' => '红酒',
  ),
  515 => 
  array (
    'cat_id' => '515',
    'cat_name' => '滋补酒',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '515',
    'name' => '滋补酒',
  ),
  512 => 
  array (
    'cat_id' => '512',
    'cat_name' => '黄酒',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '512',
    'name' => '黄酒',
  ),
  513 => 
  array (
    'cat_id' => '513',
    'cat_name' => '啤酒系列',
    'measure_unit' => '',
    'parent_id' => '502',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '513',
    'name' => '啤酒系列',
  ),
  370 => 
  array (
    'cat_id' => '370',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '5',
    'level' => 0,
    'id' => '370',
    'name' => '休闲食品',
  ),
  471 => 
  array (
    'cat_id' => '471',
    'cat_name' => '饼干糕点',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '471',
    'name' => '饼干糕点',
  ),
  491 => 
  array (
    'cat_id' => '491',
    'cat_name' => '传统糕点',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '491',
    'name' => '传统糕点',
  ),
  488 => 
  array (
    'cat_id' => '488',
    'cat_name' => '沙琪玛',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '488',
    'name' => '沙琪玛',
  ),
  485 => 
  array (
    'cat_id' => '485',
    'cat_name' => '饼干',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 2,
    'id' => '485',
    'name' => '饼干',
  ),
  489 => 
  array (
    'cat_id' => '489',
    'cat_name' => '蛋黄派/巧克力派',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '489',
    'name' => '蛋黄派/巧克力派',
  ),
  486 => 
  array (
    'cat_id' => '486',
    'cat_name' => '威化',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '486',
    'name' => '威化',
  ),
  490 => 
  array (
    'cat_id' => '490',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '490',
    'name' => '面包',
  ),
  487 => 
  array (
    'cat_id' => '487',
    'cat_name' => '曲奇',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '487',
    'name' => '曲奇',
  ),
  482 => 
  array (
    'cat_id' => '482',
    'cat_name' => '糖果/巧克力',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '1',
    'level' => 1,
    'id' => '482',
    'name' => '糖果/巧克力',
  ),
  495 => 
  array (
    'cat_id' => '495',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '482',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '495',
    'name' => '糖果',
  ),
  496 => 
  array (
    'cat_id' => '496',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '482',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '496',
    'name' => '巧克力',
  ),
  472 => 
  array (
    'cat_id' => '472',
    'cat_name' => '膨化食品',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '472',
    'name' => '膨化食品',
  ),
  494 => 
  array (
    'cat_id' => '494',
    'cat_name' => '麦烧系列',
    'measure_unit' => '',
    'parent_id' => '472',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '494',
    'name' => '麦烧系列',
  ),
  492 => 
  array (
    'cat_id' => '492',
    'cat_name' => '薯片',
    'measure_unit' => '',
    'parent_id' => '472',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 2,
    'id' => '492',
    'name' => '薯片',
  ),
  493 => 
  array (
    'cat_id' => '493',
    'cat_name' => '薯条',
    'measure_unit' => '',
    'parent_id' => '472',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '493',
    'name' => '薯条',
  ),
  483 => 
  array (
    'cat_id' => '483',
    'cat_name' => '坚果蜜饯',
    'measure_unit' => '',
    'parent_id' => '370',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '483',
    'name' => '坚果蜜饯',
  ),
  498 => 
  array (
    'cat_id' => '498',
    'cat_name' => '炒货系列',
    'measure_unit' => '',
    'parent_id' => '483',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 2,
    'id' => '498',
    'name' => '炒货系列',
  ),
  499 => 
  array (
    'cat_id' => '499',
    'cat_name' => '蜜饯果干',
    'measure_unit' => '',
    'parent_id' => '483',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '499',
    'name' => '蜜饯果干',
  ),
  500 => 
  array (
    'cat_id' => '500',
    'cat_name' => '话梅',
    'measure_unit' => '',
    'parent_id' => '483',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '500',
    'name' => '话梅',
  ),
  497 => 
  array (
    'cat_id' => '497',
    'cat_name' => '坚果休闲',
    'measure_unit' => '',
    'parent_id' => '483',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '497',
    'name' => '坚果休闲',
  ),
  481 => 
  array (
    'cat_id' => '481',
    'cat_name' => '其他产品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '481',
    'name' => '其他产品',
  ),
  477 => 
  array (
    'cat_id' => '477',
    'cat_name' => '粮油干货',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '477',
    'name' => '粮油干货',
  ),
  603 => 
  array (
    'cat_id' => '603',
    'cat_name' => '米面杂粮',
    'measure_unit' => '',
    'parent_id' => '477',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '603',
    'name' => '米面杂粮',
  ),
  616 => 
  array (
    'cat_id' => '616',
    'cat_name' => '粉丝',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '616',
    'name' => '粉丝',
  ),
  613 => 
  array (
    'cat_id' => '613',
    'cat_name' => '大米',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '613',
    'name' => '大米',
  ),
  617 => 
  array (
    'cat_id' => '617',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '617',
    'name' => '其他未分类',
  ),
  614 => 
  array (
    'cat_id' => '614',
    'cat_name' => '面皮',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '614',
    'name' => '面皮',
  ),
  615 => 
  array (
    'cat_id' => '615',
    'cat_name' => '面粉',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '615',
    'name' => '面粉',
  ),
  612 => 
  array (
    'cat_id' => '612',
    'cat_name' => '面条',
    'measure_unit' => '',
    'parent_id' => '603',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '612',
    'name' => '面条',
  ),
  604 => 
  array (
    'cat_id' => '604',
    'cat_name' => '干货系列',
    'measure_unit' => '',
    'parent_id' => '477',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '604',
    'name' => '干货系列',
  ),
  622 => 
  array (
    'cat_id' => '622',
    'cat_name' => '海带/干菜',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '622',
    'name' => '海带/干菜',
  ),
  619 => 
  array (
    'cat_id' => '619',
    'cat_name' => '木耳/银耳',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '619',
    'name' => '木耳/银耳',
  ),
  623 => 
  array (
    'cat_id' => '623',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '623',
    'name' => '其他未分类',
  ),
  620 => 
  array (
    'cat_id' => '620',
    'cat_name' => '莲子/枣子',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '620',
    'name' => '莲子/枣子',
  ),
  621 => 
  array (
    'cat_id' => '621',
    'cat_name' => '菌菇类',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '621',
    'name' => '菌菇类',
  ),
  618 => 
  array (
    'cat_id' => '618',
    'cat_name' => '桂圆/荔枝',
    'measure_unit' => '',
    'parent_id' => '604',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '618',
    'name' => '桂圆/荔枝',
  ),
  602 => 
  array (
    'cat_id' => '602',
    'cat_name' => '食用油',
    'measure_unit' => '',
    'parent_id' => '477',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 1,
    'id' => '602',
    'name' => '食用油',
  ),
  609 => 
  array (
    'cat_id' => '609',
    'cat_name' => '花生油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '609',
    'name' => '花生油',
  ),
  606 => 
  array (
    'cat_id' => '606',
    'cat_name' => '调和油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '606',
    'name' => '调和油',
  ),
  610 => 
  array (
    'cat_id' => '610',
    'cat_name' => '葵花籽油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '610',
    'name' => '葵花籽油',
  ),
  607 => 
  array (
    'cat_id' => '607',
    'cat_name' => '菜籽油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '607',
    'name' => '菜籽油',
  ),
  611 => 
  array (
    'cat_id' => '611',
    'cat_name' => '玉米油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '611',
    'name' => '玉米油',
  ),
  608 => 
  array (
    'cat_id' => '608',
    'cat_name' => '稻米油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '608',
    'name' => '稻米油',
  ),
  605 => 
  array (
    'cat_id' => '605',
    'cat_name' => '大豆油',
    'measure_unit' => '',
    'parent_id' => '602',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '605',
    'name' => '大豆油',
  ),
  474 => 
  array (
    'cat_id' => '474',
    'cat_name' => '日用百货',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => '199',
    'level' => 0,
    'id' => '474',
    'name' => '日用百货',
  ),
  544 => 
  array (
    'cat_id' => '544',
    'cat_name' => '衣物清洁',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '544',
    'name' => '衣物清洁',
  ),
  558 => 
  array (
    'cat_id' => '558',
    'cat_name' => '除霉剂',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '558',
    'name' => '除霉剂',
  ),
  555 => 
  array (
    'cat_id' => '555',
    'cat_name' => '洗衣皂',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '555',
    'name' => '洗衣皂',
  ),
  556 => 
  array (
    'cat_id' => '556',
    'cat_name' => '护理液',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '556',
    'name' => '护理液',
  ),
  553 => 
  array (
    'cat_id' => '553',
    'cat_name' => '洗衣粉',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 2,
    'id' => '553',
    'name' => '洗衣粉',
  ),
  557 => 
  array (
    'cat_id' => '557',
    'cat_name' => '漂渍剂',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '557',
    'name' => '漂渍剂',
  ),
  554 => 
  array (
    'cat_id' => '554',
    'cat_name' => '洗衣液',
    'measure_unit' => '',
    'parent_id' => '544',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
    'level' => 2,
    'id' => '554',
    'name' => '洗衣液',
  ),
  548 => 
  array (
    'cat_id' => '548',
    'cat_name' => '洗发护发',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => '18',
    'level' => 1,
    'id' => '548',
    'name' => '洗发护发',
  ),
  581 => 
  array (
    'cat_id' => '581',
    'cat_name' => '染发',
    'measure_unit' => '',
    'parent_id' => '548',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '581',
    'name' => '染发',
  ),
  582 => 
  array (
    'cat_id' => '582',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '548',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '582',
    'name' => '套装',
  ),
  579 => 
  array (
    'cat_id' => '579',
    'cat_name' => '洗发水',
    'measure_unit' => '',
    'parent_id' => '548',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '40',
    'level' => 2,
    'id' => '579',
    'name' => '洗发水',
  ),
  580 => 
  array (
    'cat_id' => '580',
    'cat_name' => '护发素',
    'measure_unit' => '',
    'parent_id' => '548',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '580',
    'name' => '护发素',
  ),
  550 => 
  array (
    'cat_id' => '550',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '550',
    'name' => '口腔护理',
  ),
  584 => 
  array (
    'cat_id' => '584',
    'cat_name' => '牙刷',
    'measure_unit' => '',
    'parent_id' => '550',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '584',
    'name' => '牙刷',
  ),
  585 => 
  array (
    'cat_id' => '585',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '550',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '585',
    'name' => '套装',
  ),
  583 => 
  array (
    'cat_id' => '583',
    'cat_name' => '牙膏',
    'measure_unit' => '',
    'parent_id' => '550',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '57',
    'level' => 2,
    'id' => '583',
    'name' => '牙膏',
  ),
  552 => 
  array (
    'cat_id' => '552',
    'cat_name' => '纸品/一次性用品',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '26',
    'level' => 1,
    'id' => '552',
    'name' => '纸品/一次性用品',
  ),
  593 => 
  array (
    'cat_id' => '593',
    'cat_name' => '一次性纸杯',
    'measure_unit' => '',
    'parent_id' => '552',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 2,
    'id' => '593',
    'name' => '一次性纸杯',
  ),
  590 => 
  array (
    'cat_id' => '590',
    'cat_name' => '卫生纸',
    'measure_unit' => '',
    'parent_id' => '552',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '590',
    'name' => '卫生纸',
  ),
  662 => 
  array (
    'cat_id' => '662',
    'cat_name' => '桌布系列',
    'measure_unit' => '',
    'parent_id' => '552',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '662',
    'name' => '桌布系列',
  ),
  591 => 
  array (
    'cat_id' => '591',
    'cat_name' => '手纸',
    'measure_unit' => '',
    'parent_id' => '552',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '591',
    'name' => '手纸',
  ),
  592 => 
  array (
    'cat_id' => '592',
    'cat_name' => '餐巾纸',
    'measure_unit' => '',
    'parent_id' => '552',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '592',
    'name' => '餐巾纸',
  ),
  549 => 
  array (
    'cat_id' => '549',
    'cat_name' => '身体护肤',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '549',
    'name' => '身体护肤',
  ),
  577 => 
  array (
    'cat_id' => '577',
    'cat_name' => '乳液面霜',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '577',
    'name' => '乳液面霜',
  ),
  574 => 
  array (
    'cat_id' => '574',
    'cat_name' => '润肤乳',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '574',
    'name' => '润肤乳',
  ),
  578 => 
  array (
    'cat_id' => '578',
    'cat_name' => '防晒',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '578',
    'name' => '防晒',
  ),
  575 => 
  array (
    'cat_id' => '575',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '575',
    'name' => '洁面',
  ),
  576 => 
  array (
    'cat_id' => '576',
    'cat_name' => '爽肤水',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '576',
    'name' => '爽肤水',
  ),
  573 => 
  array (
    'cat_id' => '573',
    'cat_name' => '沐浴乳',
    'measure_unit' => '',
    'parent_id' => '549',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '22',
    'level' => 2,
    'id' => '573',
    'name' => '沐浴乳',
  ),
  545 => 
  array (
    'cat_id' => '545',
    'cat_name' => '家庭清洁',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '10',
    'goods_num' => '3',
    'level' => 1,
    'id' => '545',
    'name' => '家庭清洁',
  ),
  561 => 
  array (
    'cat_id' => '561',
    'cat_name' => '洁厕用品',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '561',
    'name' => '洁厕用品',
  ),
  565 => 
  array (
    'cat_id' => '565',
    'cat_name' => '垃圾桶',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '565',
    'name' => '垃圾桶',
  ),
  562 => 
  array (
    'cat_id' => '562',
    'cat_name' => '香皂',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 2,
    'id' => '562',
    'name' => '香皂',
  ),
  559 => 
  array (
    'cat_id' => '559',
    'cat_name' => '洗手液',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '559',
    'name' => '洗手液',
  ),
  566 => 
  array (
    'cat_id' => '566',
    'cat_name' => '拖把',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '566',
    'name' => '拖把',
  ),
  563 => 
  array (
    'cat_id' => '563',
    'cat_name' => '油污清洗剂',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '563',
    'name' => '油污清洗剂',
  ),
  560 => 
  array (
    'cat_id' => '560',
    'cat_name' => '洗洁精',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '560',
    'name' => '洗洁精',
  ),
  567 => 
  array (
    'cat_id' => '567',
    'cat_name' => '百洁布/钢丝球/锅碗刷',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '567',
    'name' => '百洁布/钢丝球/锅碗刷',
  ),
  564 => 
  array (
    'cat_id' => '564',
    'cat_name' => '垃圾袋',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '564',
    'name' => '垃圾袋',
  ),
  661 => 
  array (
    'cat_id' => '661',
    'cat_name' => '保鲜膜/保鲜袋',
    'measure_unit' => '',
    'parent_id' => '545',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 2,
    'id' => '661',
    'name' => '保鲜膜/保鲜袋',
  ),
  546 => 
  array (
    'cat_id' => '546',
    'cat_name' => '驱虫驱蚊用品',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '546',
    'name' => '驱虫驱蚊用品',
  ),
  571 => 
  array (
    'cat_id' => '571',
    'cat_name' => '花露水',
    'measure_unit' => '',
    'parent_id' => '546',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '571',
    'name' => '花露水',
  ),
  568 => 
  array (
    'cat_id' => '568',
    'cat_name' => '灭鼠/杀虫剂',
    'measure_unit' => '',
    'parent_id' => '546',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 2,
    'id' => '568',
    'name' => '灭鼠/杀虫剂',
  ),
  572 => 
  array (
    'cat_id' => '572',
    'cat_name' => '其他驱虫用品',
    'measure_unit' => '',
    'parent_id' => '546',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '572',
    'name' => '其他驱虫用品',
  ),
  569 => 
  array (
    'cat_id' => '569',
    'cat_name' => '蚊香',
    'measure_unit' => '',
    'parent_id' => '546',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '19',
    'level' => 2,
    'id' => '569',
    'name' => '蚊香',
  ),
  570 => 
  array (
    'cat_id' => '570',
    'cat_name' => '吸湿/防蛀',
    'measure_unit' => '',
    'parent_id' => '546',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '570',
    'name' => '吸湿/防蛀',
  ),
  551 => 
  array (
    'cat_id' => '551',
    'cat_name' => '女性护理',
    'measure_unit' => '',
    'parent_id' => '474',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '551',
    'name' => '女性护理',
  ),
  587 => 
  array (
    'cat_id' => '587',
    'cat_name' => '卫生护垫',
    'measure_unit' => '',
    'parent_id' => '551',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '587',
    'name' => '卫生护垫',
  ),
  588 => 
  array (
    'cat_id' => '588',
    'cat_name' => '私密护理',
    'measure_unit' => '',
    'parent_id' => '551',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '588',
    'name' => '私密护理',
  ),
  589 => 
  array (
    'cat_id' => '589',
    'cat_name' => '脱毛膏',
    'measure_unit' => '',
    'parent_id' => '551',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '589',
    'name' => '脱毛膏',
  ),
  586 => 
  array (
    'cat_id' => '586',
    'cat_name' => '卫生巾',
    'measure_unit' => '',
    'parent_id' => '551',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '586',
    'name' => '卫生巾',
  ),
  478 => 
  array (
    'cat_id' => '478',
    'cat_name' => '茶冲/乳品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '478',
    'name' => '茶冲/乳品',
  ),
  625 => 
  array (
    'cat_id' => '625',
    'cat_name' => '咖啡',
    'measure_unit' => '',
    'parent_id' => '478',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '625',
    'name' => '咖啡',
  ),
  635 => 
  array (
    'cat_id' => '635',
    'cat_name' => '咖啡粉',
    'measure_unit' => '',
    'parent_id' => '625',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '635',
    'name' => '咖啡粉',
  ),
  636 => 
  array (
    'cat_id' => '636',
    'cat_name' => '咖啡伴侣',
    'measure_unit' => '',
    'parent_id' => '625',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '636',
    'name' => '咖啡伴侣',
  ),
  633 => 
  array (
    'cat_id' => '633',
    'cat_name' => '速溶咖啡',
    'measure_unit' => '',
    'parent_id' => '625',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '633',
    'name' => '速溶咖啡',
  ),
  634 => 
  array (
    'cat_id' => '634',
    'cat_name' => '咖啡豆',
    'measure_unit' => '',
    'parent_id' => '625',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '634',
    'name' => '咖啡豆',
  ),
  626 => 
  array (
    'cat_id' => '626',
    'cat_name' => '茗茶',
    'measure_unit' => '',
    'parent_id' => '478',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '626',
    'name' => '茗茶',
  ),
  641 => 
  array (
    'cat_id' => '641',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '626',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '641',
    'name' => '其他未分类',
  ),
  638 => 
  array (
    'cat_id' => '638',
    'cat_name' => '花草茶',
    'measure_unit' => '',
    'parent_id' => '626',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '638',
    'name' => '花草茶',
  ),
  639 => 
  array (
    'cat_id' => '639',
    'cat_name' => '绿茶',
    'measure_unit' => '',
    'parent_id' => '626',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '639',
    'name' => '绿茶',
  ),
  640 => 
  array (
    'cat_id' => '640',
    'cat_name' => '红茶',
    'measure_unit' => '',
    'parent_id' => '626',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '640',
    'name' => '红茶',
  ),
  637 => 
  array (
    'cat_id' => '637',
    'cat_name' => '乌龙茶',
    'measure_unit' => '',
    'parent_id' => '626',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '637',
    'name' => '乌龙茶',
  ),
  627 => 
  array (
    'cat_id' => '627',
    'cat_name' => '营养保健',
    'measure_unit' => '',
    'parent_id' => '478',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '627',
    'name' => '营养保健',
  ),
  645 => 
  array (
    'cat_id' => '645',
    'cat_name' => '鱼油/磷脂',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '645',
    'name' => '鱼油/磷脂',
  ),
  642 => 
  array (
    'cat_id' => '642',
    'cat_name' => '蛋白质/氨基酸',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '642',
    'name' => '蛋白质/氨基酸',
  ),
  646 => 
  array (
    'cat_id' => '646',
    'cat_name' => '西洋参/人参',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '646',
    'name' => '西洋参/人参',
  ),
  643 => 
  array (
    'cat_id' => '643',
    'cat_name' => '维生素/钙',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '643',
    'name' => '维生素/钙',
  ),
  647 => 
  array (
    'cat_id' => '647',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '647',
    'name' => '其他未分类',
  ),
  644 => 
  array (
    'cat_id' => '644',
    'cat_name' => '保健饮品/酒',
    'measure_unit' => '',
    'parent_id' => '627',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '644',
    'name' => '保健饮品/酒',
  ),
  624 => 
  array (
    'cat_id' => '624',
    'cat_name' => '牛奶',
    'measure_unit' => '',
    'parent_id' => '478',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '624',
    'name' => '牛奶',
  ),
  632 => 
  array (
    'cat_id' => '632',
    'cat_name' => '风味奶',
    'measure_unit' => '',
    'parent_id' => '624',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '632',
    'name' => '风味奶',
  ),
  629 => 
  array (
    'cat_id' => '629',
    'cat_name' => '儿童奶',
    'measure_unit' => '',
    'parent_id' => '624',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '629',
    'name' => '儿童奶',
  ),
  630 => 
  array (
    'cat_id' => '630',
    'cat_name' => '酸奶',
    'measure_unit' => '',
    'parent_id' => '624',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '630',
    'name' => '酸奶',
  ),
  631 => 
  array (
    'cat_id' => '631',
    'cat_name' => '豆奶',
    'measure_unit' => '',
    'parent_id' => '624',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '631',
    'name' => '豆奶',
  ),
  628 => 
  array (
    'cat_id' => '628',
    'cat_name' => '纯牛奶',
    'measure_unit' => '',
    'parent_id' => '624',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '628',
    'name' => '纯牛奶',
  ),
  475 => 
  array (
    'cat_id' => '475',
    'cat_name' => '厨房调味',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '475',
    'name' => '厨房调味',
  ),
  517 => 
  array (
    'cat_id' => '517',
    'cat_name' => '调味酱',
    'measure_unit' => '',
    'parent_id' => '475',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '7',
    'goods_num' => '1',
    'level' => 1,
    'id' => '517',
    'name' => '调味酱',
  ),
  534 => 
  array (
    'cat_id' => '534',
    'cat_name' => '肉味酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '534',
    'name' => '肉味酱',
  ),
  531 => 
  array (
    'cat_id' => '531',
    'cat_name' => '番茄酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '531',
    'name' => '番茄酱',
  ),
  528 => 
  array (
    'cat_id' => '528',
    'cat_name' => '豆瓣酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 2,
    'id' => '528',
    'name' => '豆瓣酱',
  ),
  532 => 
  array (
    'cat_id' => '532',
    'cat_name' => '花生酱/芝麻酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '532',
    'name' => '花生酱/芝麻酱',
  ),
  529 => 
  array (
    'cat_id' => '529',
    'cat_name' => '辣椒酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '529',
    'name' => '辣椒酱',
  ),
  533 => 
  array (
    'cat_id' => '533',
    'cat_name' => '鱼子酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '533',
    'name' => '鱼子酱',
  ),
  530 => 
  array (
    'cat_id' => '530',
    'cat_name' => '沙拉/蛋黄酱',
    'measure_unit' => '',
    'parent_id' => '517',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '530',
    'name' => '沙拉/蛋黄酱',
  ),
  519 => 
  array (
    'cat_id' => '519',
    'cat_name' => '其他厨房调料',
    'measure_unit' => '',
    'parent_id' => '475',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '519',
    'name' => '其他厨房调料',
  ),
  541 => 
  array (
    'cat_id' => '541',
    'cat_name' => '调味汁',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '541',
    'name' => '调味汁',
  ),
  538 => 
  array (
    'cat_id' => '538',
    'cat_name' => '花椒油',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '538',
    'name' => '花椒油',
  ),
  542 => 
  array (
    'cat_id' => '542',
    'cat_name' => '生粉/食品添加',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '542',
    'name' => '生粉/食品添加',
  ),
  539 => 
  array (
    'cat_id' => '539',
    'cat_name' => '麻油',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '539',
    'name' => '麻油',
  ),
  536 => 
  array (
    'cat_id' => '536',
    'cat_name' => '蚝油',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '536',
    'name' => '蚝油',
  ),
  543 => 
  array (
    'cat_id' => '543',
    'cat_name' => '其他蛋制品',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '543',
    'name' => '其他蛋制品',
  ),
  540 => 
  array (
    'cat_id' => '540',
    'cat_name' => '豉油',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '540',
    'name' => '豉油',
  ),
  537 => 
  array (
    'cat_id' => '537',
    'cat_name' => '香油',
    'measure_unit' => '',
    'parent_id' => '519',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '537',
    'name' => '香油',
  ),
  516 => 
  array (
    'cat_id' => '516',
    'cat_name' => '调味料',
    'measure_unit' => '',
    'parent_id' => '475',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '516',
    'name' => '调味料',
  ),
  527 => 
  array (
    'cat_id' => '527',
    'cat_name' => '其他调味料',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 2,
    'id' => '527',
    'name' => '其他调味料',
  ),
  524 => 
  array (
    'cat_id' => '524',
    'cat_name' => '味精/鸡精',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 2,
    'id' => '524',
    'name' => '味精/鸡精',
  ),
  521 => 
  array (
    'cat_id' => '521',
    'cat_name' => '醋',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '521',
    'name' => '醋',
  ),
  525 => 
  array (
    'cat_id' => '525',
    'cat_name' => '汤料/炒菜料',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 2,
    'id' => '525',
    'name' => '汤料/炒菜料',
  ),
  522 => 
  array (
    'cat_id' => '522',
    'cat_name' => '料酒',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '522',
    'name' => '料酒',
  ),
  526 => 
  array (
    'cat_id' => '526',
    'cat_name' => '火锅底料',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '526',
    'name' => '火锅底料',
  ),
  523 => 
  array (
    'cat_id' => '523',
    'cat_name' => '盐',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '523',
    'name' => '盐',
  ),
  520 => 
  array (
    'cat_id' => '520',
    'cat_name' => '酱油',
    'measure_unit' => '',
    'parent_id' => '516',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '38',
    'level' => 2,
    'id' => '520',
    'name' => '酱油',
  ),
  480 => 
  array (
    'cat_id' => '480',
    'cat_name' => '办公文体',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 0,
    'id' => '480',
    'name' => '办公文体',
  ),
  648 => 
  array (
    'cat_id' => '648',
    'cat_name' => '办公用品',
    'measure_unit' => '',
    'parent_id' => '480',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '648',
    'name' => '办公用品',
  ),
  655 => 
  array (
    'cat_id' => '655',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '648',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '655',
    'name' => '其他未分类',
  ),
  652 => 
  array (
    'cat_id' => '652',
    'cat_name' => '计算器',
    'measure_unit' => '',
    'parent_id' => '648',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '652',
    'name' => '计算器',
  ),
  653 => 
  array (
    'cat_id' => '653',
    'cat_name' => '订书机',
    'measure_unit' => '',
    'parent_id' => '648',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '653',
    'name' => '订书机',
  ),
  654 => 
  array (
    'cat_id' => '654',
    'cat_name' => '纸笔系列',
    'measure_unit' => '',
    'parent_id' => '648',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '654',
    'name' => '纸笔系列',
  ),
  650 => 
  array (
    'cat_id' => '650',
    'cat_name' => '打印纸',
    'measure_unit' => '',
    'parent_id' => '648',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '650',
    'name' => '打印纸',
  ),
  649 => 
  array (
    'cat_id' => '649',
    'cat_name' => '学习用品',
    'measure_unit' => '',
    'parent_id' => '480',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '649',
    'name' => '学习用品',
  ),
  658 => 
  array (
    'cat_id' => '658',
    'cat_name' => '橡皮',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '658',
    'name' => '橡皮',
  ),
  659 => 
  array (
    'cat_id' => '659',
    'cat_name' => '铅笔刀',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '659',
    'name' => '铅笔刀',
  ),
  656 => 
  array (
    'cat_id' => '656',
    'cat_name' => '笔',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '656',
    'name' => '笔',
  ),
  660 => 
  array (
    'cat_id' => '660',
    'cat_name' => '其他未分类',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '660',
    'name' => '其他未分类',
  ),
  657 => 
  array (
    'cat_id' => '657',
    'cat_name' => '本子',
    'measure_unit' => '',
    'parent_id' => '649',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '657',
    'name' => '本子',
  ),
);
?>